### ISSUE TITLE
NullPointerExceptio error when trying to use mr list command

### ISSUE THREAD

**Issue by doda-s** [PedRo-HenRique-14/finance-planner#53]
If a JSON file is loaded but no elements are in the monthlyRegister list, the `List<MonthlyRegister> monthlyRegisters` list of the `Spreadsheet` class is null.
https://github.com/doda-s/finance-planner/blob/3b51fe7b524029b14c3b64ef2d97fef24f913ea3/src/main/java/me/dodas/financeplanner/models/Spreadsheet.java#L14
When trying to access a list element through `for`, a `NullPointerException` error is thrown.
https://github.com/doda-s/finance-planner/blob/3b51fe7b524029b14c3b64ef2d97fef24f913ea3/src/main/java/me/dodas/financeplanner/subcommands/MonthlyRegisterListSubCommand.java#L50
To solve, simply check if the list is null, before starting the for.

**Comment by ssumik** [comment]
Foi fixed rapaz
